#!/bin/bash

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: ./ask <article_html> <N>"
  exit $E_BADARGS
fi

export NLTK_DATA=/afs/andrew.cmu.edu/usr6/ericgan/nltk_data
export PYTHONPATH=/afs/andrew.cmu.edu/usr6/ericgan/.local/lib/python2.6/sites-packages

cd src
./ask.py ../$1 $2
